revert to build script approach
can't resolve cargo crate ref err, giving up

warning: rust-canto@0.3.2: Dictionary trie.dat successfully generated by build.rs
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 14.70s
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: /home/vin100/rust-canto/target/package/rust-canto-0.3.2/data/trie.dat

  To proceed despite this, pass the `--no-verify` flag.