build: added include attribute in TOML
To solve this error
```
$ cargo publish
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `xtask` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```
Thank to Gemini again.